apiVersion: v1
kind: Pod
metadata:
    name: metadataservice
    labels:
        app: metadataserviceapp
spec:
    containers:
    - name: metaservice
      image: luckyganesh/metadata-service:v1
      ports:
        - containerPort: 8080